name: Deploy Server to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy Express Server
    runs-on: ubuntu-latest

    environment: NEXTAUTH_SECRET
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="$PATH:/usr/local/bin:/usr/bin"

            cd /var/www/casadimoda-server
            git checkout -- package-lock.json
            git pull origin main
            echo "NODE_ENV=production" > .env
            echo "PORT=${{ secrets.SERVER_PORT }}" >> .env
            echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> .env
            echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> .env
            echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> .env
            echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
            echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
            npm ci
            npm run build
            pm2 restart casadimoda-server --update-env
            pm2 save
